import SwiftUI

// Auto-generated by Last Mile runner — do not edit manually
enum NavBarStyle { case colored, transparent, hidden }

enum AppConfig {
    static let appURL        = URL(string: "https://example.com")!
    static let appName       = "My App"
    static let primaryColor  = Color(hex: "#3B82F6")
    static let navBarStyle   = NavBarStyle.colored
    static let pullToRefresh = true
    static let allowZoom     = true
}
